language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3"
install:
  - pip install pytest coveralls
  - pip install .
script:
  - pytest
  - coverage run --source=poliedro_donate setup.py test
after_success: coveralls