language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3"
install:
  - pip install pytest pytest-flask pytest-runner coveralls
  - pip install .
  - pip install https://github.com/Depau/braintreehttp_python-noparseresponse/archive/master.zip
script:
  - pytest
  - coverage run --source=poliedro_donate setup.py test
after_success: coveralls